### ISSUE TITLE
Support model only

### ISSUE THREAD

**Issue by lobro-randd** [r-dinsur/apollo#20]
Need to map this Model name to a list of existing Make.

ex.

User: Give me the premium for a Corrola
(searches for make that have "corolla" model) = Toyota
(default latest model year for Toyota Corolla) = 2017

Alexa: "your premium is..."

**Comment by lvallier-intact** [comment]
vehicleList enum has been made and the implementation too, the implementation for the assumeYear has been done too, we could test it with Alexa now 
@lobro-randd
